### quarkus
quarkus:
  application:
    name: sample-project
  profile: "${PROFILE:local}"
  config:
    profile:
      parent: "common"
  ### for Web server
  http:
    port: 8100
  shutdown:
    timeout: 120S
  thread-pool:
    core-threads: 2
    max-threads: 10
    shutdown-timeout: 120S
    shutdown-interrupt: 60S
    keep-alive-time: 60S
  ### for health check
  smallrye-health:
    root-path: "health"
    liveness-path: "live"
    readiness-path: "ready"
    ui:
      enable: false
  ### for DB
  datasource:
    db-kind: mariadb
#    username: ${DB_USER:app_user}
#    password: ${DB_PASSWARD:app_user}
    username: root
    password: root
    jdbc:
#      url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/sample_project}
      url: ${DB_URL:jdbc:mysql://127.0.0.1:${MYSQL_TCP_3306:3306}/sample_project?useSSL=false}
      driver: org.mariadb.jdbc.Driver
      initial-size: 0
      min-size: 3
      max-size: 10
      idle-removal-interval: 2M
  flyway:
    clean-at-start: false
    clean-disabled: true
    migrate-at-start: false
  ### for log
  log:
    level: ${LOG_LEVEL:INFO}

#logging:
#  level:
#    root: ${LOG_LEVEL:INFO}
#    com.nekose.sampleproject: ${APP_LOG_LEVEL:INFO}

#sample-project:
#  redis:
#    prefix: example-data-
#    ttlSeconds: 604800
#  scheduler:
#    cron: ${SCHEDULER_CRON:0/15 * * * * *}
#  crypto:
#    key: ${SAMPLE_CRYPTO_KEY:testCryptoKey}
#    hash-salt: ${SAMPLE_HASH_SALT:testSaltString}

# for API Client
dummy-api/mp-rest/url: ${DUMMY_API_HOST_URL:http://localhost:${MOCK_TCP_8080:9999}/dummy}
dummy-api/mp-rest/connectTimeout: 10000
dummy-api/mp-rest/readTimeout: 15000
dummy-api:
  endpoint: ${DUMMY_API_ENDPOINT:/v1/dummyApi/{id}}
  max-connection: 50
  retry-limit: 3
