### quarkus
quarkus:
  ### for health check
  smallrye-health:
    ui:
      enable: true
  ### for DB
  datasource:
    username: root
    password: root
    jdbc:
      url: ${DB_URL:jdbc:mysql://127.0.0.1:${MYSQL_TCP_3306:3306}/sample_project?useSSL=false}
  flyway:
    clean-at-start: true
    clean-disabled: false
    migrate-at-start: true
    locations: ["classpath:/db/migration"]
  ### for log
  log:
    level:
      com.nekose.sampleproject: DEBUG

